[package]
name = "infra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain={path="../domain"}
chrono = { workspace=true}
serde_json = {workspace=true}
thiserror = {workspace=true}